version: "3.8"

networks:
  servers:

services:
  balancer:
    build: .
    command: balancer
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    command: server
    environment:
      - SERVER_NAME=testrnasap
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    command: server
    environment:
      - SERVER_NAME=server2
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    command: server
    environment:
      - SERVER_NAME=server3
    networks:
      - servers
    ports:
      - "8082:8080"

  dbserver:
    build: .
    command: dbserver
    networks:
      - servers
    ports:
      - "8083:8083"
    volumes:
      - ./db-files:/opt/practice-4/db-files